base_url = "https://connorkooistra.github.io"
title = "Connor Kooistra"
description = "This is my personal portfolio"
author = "Connor Kooistra"

compile_sass = true
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here