base_url = "https://cdkooistra.github.io"
title = "Portfolio cdkooistra"
description = "Welcome to my personal resume page. Here you can find information about my professional experience, skills, and projects."
author = "Connor Kooistra"

compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
github_avatar = "https://github.com/cdkooistra.png"